services:
  facilitation:
    image: public.ecr.aws/h1n7c6s4/tfm/facilitation:latest
    ports:
      - "8080:8080"
    env_file: .env.local
    volumes:
      - ./docs/experiments/results:/app/docs/experiments/results
      - ./history.db:/app/history.db
    restart: unless-stopped
